### ISSUE TITLE
Update Config File for sun-cli

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/sun-network#227]
config file shows   `gateway_address = "THCvxQXnVTfGtM1xTg6Edk946wxRzdAi5d"` whereas the docs at https://tron.network/sunnetwork/doc/guide/#_1-dappchain-node-list shows the gateway address is TWaPZru6PR5VjgT4sJrrZ481Zgp3iJ8Rfo

does this need to be updated?

**Comment by taihaofu** [comment]
Correct. We will update an official version later.

**Comment by taihaofu** [comment]
@bondibox I have updated it [here](https://github.com/tronprotocol/sun-network/blob/develop/sun-cli/src/main/resources/config.conf). Thank you for the correctness.
