### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: this.isAddress is not a function

### ISSUE THREAD

**Issue by mong-totogo** [tronprotocol/sun-network#237]
ERROR Error: Uncaught (in promise): TypeError: this.isAddress is not a function
TypeError: this.isAddress is not a function
    at e.value (SunWeb.node.js:1)
    at new e (SunWeb.node.js:1)

**Comment by mong-totogo** [comment]
> ERROR Error: Uncaught (in promise): TypeError: this.isAddress is not a function
> TypeError: this.isAddress is not a function
> at e.value (SunWeb.node.js:1)
> at new e (SunWeb.node.js:1)

**Comment by AnhHoangQuach** [comment]
how to fix that can u say to me
