### ISSUE TITLE
what it takes to migrate

### ISSUE THREAD

**Issue by julie447** [tronprotocol/sun-network#256]
I would have to understand what it takes to migrate since we have a very large network of connected components with funds locked in.

**Comment by taihaofu** [comment]
You can check [here](https://github.com/tronprotocol/sun-network/blob/feature/documents/documentation/docs/guide/README.md#viii-build-your-dapp-on-dappchain) for more information

**Comment by taihaofu** [comment]
Please feel free to ask any questions, we would like to help.
