### ISSUE TITLE
/front/api/config.js seems to need to update

### ISSUE THREAD

**Issue by zem007** [tronprotocol/sun-network#259]
It seems that some codes in /Demo folder needs to be updated. eg. the config.js in the /front folder:

mainGatewayAddress: 'TGHxhFu4jV4XqMGmk3tEQdSeihWVHE9kBP',
sideGatewayAddress: 'TBHr5KpbA7oACUysTKxHiAD7c6X6nkZii1',
chainId: '41455cb714d762dc46d490eab37bba67b0ba910a59',

I believe those information are no longer useful, and they should be changed as discribed in _**https://tron.network/sunnetwork/doc/guide/**_

**Comment by taihaofu** [comment]
I see. Will change them later. 

Thanks.
