### ISSUE TITLE
need help in using sun sdk in android

### ISSUE THREAD

**Issue by shipunyc** [tronprotocol/sun-network#269]
The android integration had been a hard process for me:

I first figured out how to get lombok compile
then ran into the dex 64k limit
now stuck at com.google.longrunning.OperationOrBuilder dependency

Can you provide a template, that uses SunSDK in an empty Android project?

**Comment by shipunyc** [comment]
Also, it would be very helpful if the SunSDK can be available in Maven, so that I don't need to integrate using the source code.

**Comment by taihaofu** [comment]
Currently we don’t have plan to do sunsdk in maven and android. But it is a good call. We will consider that in future release.
