### ISSUE TITLE
Side-chain functional parameter settings

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/sun-network#6]
As we want to provide customization functionality for side-chain deployer, we need to give them interface to set important parameters for a chain, including but not restricted as following items:

1. block product time
2. energy/sun
3. witness numbers
4. maintenance time period
...

**Comment by taihaofu** [comment]
Done. All in args. Except time produce interval related parameters

**Comment by tabathap** [comment]
👌

**Comment by BigBlueHundids** [comment]
> As we want to provide customization functionality for side-chain deployer, we need to give them interface to set important parameters for a chain, including but not restricted as following items:
> 
> 1. block product time
> 2. energy/sun
> 3. witness numbers
> 4. maintenance time period
>    ...

**Comment by BigBlueHundids** [comment]
> As we want to provide customization functionality for side-chain deployer, we need to give them interface to set important parameters for a chain, including but not restricted as following items:
> 
> 1. block product time
> 2. energy/sun
> 3. witness numbers
> 4. maintenance time period
>    ...
