### ISSUE TITLE
Implement State tree

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/sun-network#9]
We need to implement State tree related logic to support future important validation steps

**Comment by tabathap** [comment]
👌

**Comment by tabathap** [comment]
👌

**Comment by taihaofu** [comment]
Will implement through oracle chain

**Comment by BigBlueHundids** [comment]
> We need to implement State tree related logic to support future important validation steps

**Comment by BigBlueHundids** [comment]
> Will implement through oracle chain

**Comment by BigBlueHundids** [comment]
>.

**Comment by BigBlueHundids** [comment]
>.

**Comment by BigBlueHundids** [comment]
> We need to implement State tree related logic to support future important validation steps

**Comment by BigBlueHundids** [comment]
>.

**Comment by Skylerspencer** [comment]
They took my NFT how do I recover them made themselves the creators and owners. With a fake contract how is that possible . Gave me 24 hrs to CC claim them when I brought th we m over to Tron with me.?
